apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "test-bff"
spec:
  predictor:
    model:
      args: ["--enable_docs_url=True"]
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
  explainer:
    containers:
      - name: explainer
        image: quay.io/ederignatowicz/inference-playground-llm:1
        imagePullPolicy: Always